name: Sync TFE State to S3

env:
  TFE_ORGANIZATION: ${{secrets.TFE_ORG}}
  TFE_WORKSPACE: ${{secrets.TFE_WS}}
  S3_BUCKET: ${{secrets.BUCKET_NAME}}

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual triggering

jobs:
  sync-state:
    runs-on: ubuntu-latest
    steps:
      - name: Download TFE State
        run: |
          # Get the current state version ID
          WORKSPACE_ID=$(curl \
            --header "Authorization: Bearer $TFE_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/organizations/${TFE_ORGANIZATION}/workspaces/${TFE_WORKSPACE}" \
            | jq -r '.data.id')
          
          STATE_VERSION_ID=$(curl \
            --header "Authorization: Bearer $TFE_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/workspaces/${WORKSPACE_ID}/current-state-version" \
            | jq -r '.data.id')
          
          # Download the state file
          curl \
            --header "Authorization: Bearer $TFE_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/state-versions/${STATE_VERSION_ID}/download" \
            --output terraform.tfstate

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 cp terraform.tfstate s3://${S3_BUCKET}/terraform.tfstate
